# Generated by Django 3.2 on 2023-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230530_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlegenre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
